export enum RankEnum {
    WHITE = "WHITE",
    GRAY_WHITE = "GRAY_WHITE",
    GRAY = "GRAY",
    GRAY_BLACK = "GRAY_BLACK",
    YELLOW_WHITE = "YELLOW_WHITE",
    YELLOW = "YELLOW",
    YELLOW_BLACK = "YELLOW_BLACK",
    ORANGE_WHITE = "ORANGE_WHITE",
    ORANGE = "ORANGE",
    ORANGE_BLACK = "ORANGE_BLACK",
    GREEN_WHITE = "GREEN_WHITE",
    GREEN = "GREEN",
    GREEN_BLACK = "GREEN_BLACK",
    BLUE = "BLUE",
    PURPLE = "PURPLE",
    BROWN = "BROWN",
    BLACK = "BLACK"
}